apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deploy
  labels: 
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
     app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: pingpong-api
        image: dabaus/pingpong-api
        imagePullPolicy: Never
        envFrom: 
        - configMapRef:
            name: dev-config
        ports:
        - containerPort: 8080