/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.omegapoint.pingpongapp.worker.test;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import se.omegapoint.pingpongapp.worker.*;

@SpringBootTest
public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
